name = "greeta"
main = "src/server.ts"
compatibility_date = "2024-05-18"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for storing vision-based compliments
kv_namespaces = [
  { binding = "COMPLIMENTS", id = "e75975bba7a145f882308c0c3d17f730", preview_id = "" }
]

[vars]
# You will need to add your OpenAI API Key as a secret using wrangler
# Example command: wrangler secret put OPENAI_API_KEY
# Ensure you run this command before deploying.
# The key here is just a placeholder. 